too-many-arguments-threshold = 8
too-many-lines-threshold = 150
allowed-duplicate-crates = [
    "base64",
    "block-buffer",
    "cpufeatures",
    "crypto-common",
    "dashmap",
    "digest",
    "flume",
    "getrandom",
    "heck",
    "hkdf",
    "hmac",
    "matchit",
    "r-efi",
    "rand",
    "rand_chacha",
    "rand_core",
    "reqwest",
    "rustls",
    "rustls-webpki",
    "sha1",
    "sha2",
    "strsim",
    "syn",
    "thiserror",
    "thiserror-impl",
    "tokio-rustls",
    "tokio-tungstenite",
    "tower-http",
    "tungstenite",
    "webpki-roots",
    "windows-sys",
]
