services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: wasabi_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "2345:5432"

  migrations:
    build:
      context: .
      dockerfile: tools/WasabiBot.MigrationsRunner/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PG_CONNECTION_STRING: "Host=postgres;Database=wasabi_bot;Username=postgres;Password=postgres"
  
  commands:
    build:
      context: .
      dockerfile: tools/WasabiBot.CommandsRegister/Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_TEST_GUILD_ID: ${DISCORD_TEST_GUILD_ID}

  server:
    build:
      context: .
      dockerfile: src/WasabiBot.Web/Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Database=wasabi_bot;Username=postgres;Password=postgres"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire:18889"
      OTEL_EXPORTER_OTLP_HEADERS: x-otlp-api-key=youshallnotpass
      OTEL_SERVICE_NAME: wasabi-bot
      OTEL_METRIC_EXPORT_INTERVAL: 10000
    ports:
      - "8080:8080"

  ngrok:
    image: ngrok/ngrok
    depends_on:
      - server
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_DOMAIN: ${NGROK_DOMAIN}
      TARGET_HOST: ${TARGET_HOST:-server}  # Default to "server" if not set
    command: http ${TARGET_HOST}:8080 --url=${NGROK_DOMAIN}
  
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    container_name: aspire
    ports:
      - 4317:18889
      - 18888:18888
    environment:
      DASHBOARD__FRONTEND__AUTHMODE: Unsecured
      DASHBOARD__OTLP__AUTHMODE: ApiKey
      DASHBOARD__OTLP__PRIMARYAPIKEY: youshallnotpass
