version: '3'

dotenv: ['.env']

tasks:
  default: task --list
  
  deploy:
    desc: Deploy to staging environment in Fly.io
    cmds:
      - fly deploy --config ./src/WasabiBot.Web/fly.staging.toml --dockerfile ./src/WasabiBot.Web/Dockerfile

  tf:build:
    desc: Build terraform with CDKTF
    cmds:
      - dotnet run --project infra/WasabiBot.Terraform/WasabiBot.Terraform.csproj

  tf:apply:
    desc: Apply terraform
    deps: [tf:build]
    dir: cdktf.out/stacks/WasabiBot.Terraform
    cmds:
      - terraform apply -auto-approve
