version: '3'

dotenv: ['.env']

tasks:
  default: task --list
  
  # build:
  #   desc: Build the Docker image
  #   cmds:
  #     - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/wasabi-bot:${ENVIRONMENT} . -f src/WasabiBot.Web/Dockerfile

  # push:
  #   desc: Push the image to ECR
  #   deps: [build, auth]
  #   cmds:
  #     - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/wasabi-bot:${ENVIRONMENT}

  cdktf:
    desc: Build terraform with CDKTF
    cmds:
      - dotnet run --project infra/WasabiBot.Terraform/WasabiBot.Terraform.csproj

  apply:
    desc: Apply terraform
    deps: [apply:shared]
    dir: cdktf.out/stacks/WasabiBot.Terraform
    cmds:
      - terraform apply -auto-approve

  apply:shared:
    desc: Apply terraform
    deps: [cdktf]
    dir: cdktf.out/stacks/WasabiBotShared.Terraform
    cmds:
      - terraform apply -auto-approve
  # auth:
  #   desc: Authenticate with ECR
  #   cmds:
  #     - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
