using System.Text.Json;
using WasabiBot.Discord;
using WasabiBot.Discord.Api;

namespace WasabiBot.DataAccess.Entities;

public class InteractionRecord
{
    public required long Id { get; init; }
    public required int Type { get; init; }
    public string? Data { get; init; }
    public string? GuildId { get; init; }
    public string? ChannelId { get; init; }
    public string? MemberNickname { get; init; }
    public string? MemberAvatarHash { get; init; }
    public string[]? MemberRoleIds { get; init; }
    public DateTimeOffset? MemberJoinedAt { get; init; }
    public DateTimeOffset? MemberPremiumSince { get; init; }
    public bool? MemberDeafened { get; init; }
    public bool? MemberMuted { get; init; }
    public string? MemberPermissions { get; init; }
    public required string UserId { get; init; }
    public required string Username { get; init; }
    public required string UserGlobalName { get; init; }
    public required int Version { get; init; }
    public required DateTimeOffset CreatedAt { get; init; }
    public required DateTimeOffset InsertedAt { get; set; }
    
    public static InteractionRecord FromInteractionJson(string interactionJson)
    {
        var interaction = JsonSerializer.Deserialize<Interaction>(interactionJson);
        if (interaction is null)
        {
            throw new Exception("Failed to deserialize interaction");
        }
        
        var id = long.Parse(interaction.Id);
        string? data = null;
        if (interaction.Data is not null)
        {
            data = JsonSerializer.Serialize(interaction.Data);
        }
        
        return new InteractionRecord
        {
            Id = long.Parse(interaction.Id),
            Type = (int)interaction.Type,
            Data = data,
            GuildId = interaction.GuildId,
            ChannelId = interaction.ChannelId,
            MemberNickname = interaction.GuildMember?.Nickname,
            MemberAvatarHash = interaction.GuildMember?.AvatarHash,
            MemberRoleIds = interaction.GuildMember?.RoleIds,
            MemberJoinedAt = interaction.GuildMember?.JoinedAt,
            MemberPremiumSince = interaction.GuildMember?.PremiumSince,
            MemberDeafened = interaction.GuildMember?.Deafened,
            MemberMuted = interaction.GuildMember?.Muted,
            MemberPermissions = interaction.GuildMember?.Permissions,
            UserId = (interaction.User?.Id ?? interaction.GuildMember?.User?.Id)!,
            Username = (interaction.User?.Username ?? interaction.GuildMember?.User?.Username)!,
            UserGlobalName = (interaction.User?.GlobalName ?? interaction.GuildMember?.User?.GlobalName)!,
            Version = interaction.Version,
            CreatedAt = SnowflakeHelper.ConvertToDateTimeOffset(id),
            InsertedAt = DateTimeOffset.MinValue // generated by database
        };
    }
}
