server:
  port: ${SERVER_PORT:2333}

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:youshallnotpass}
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      nico: false
      http: false
      local: false
