# fly.toml app configuration file generated for stg-wasabi-bot-web on 2024-11-02T22:16:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stg-wasabi-bot-web'
primary_region = 'dfw'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ASPNETCORE_ENVIRONMENT = "Staging"
  AWS_ROLE_ARN = "arn:aws:iam::346610971261:role/stg-wasabi-bot-web-fly-role"
