# See https://fly.io/docs/reference/configuration/ or https://json.schemastore.org/fly.json for info

app = 'stg-wasabi-bot-web'
primary_region = 'dfw'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ASPNETCORE_ENVIRONMENT = "Staging"
  AWS_ROLE_ARN = "arn:aws:iam::346610971261:role/stg-wasabi-bot-web-fly-role"
  OTEL_EXPORTER_OTLP_ENDPOINT = "http://wasabi-bot-aspire-dashboard.internal:18890"
