server:
  port: ${SERVER_PORT:2333}

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
  server:
    password: ${LAVALINK_PASSWORD:youshallnotpass}
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      nico: false
      http: true
      local: false
    soundcloudFilterOutPreviewTracks: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - MWEB
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
      - WEB
      - WEBEMBEDDED
    clientOptions:
      WEB:
        playback: false
      WEBEMBEDDED:
        playlistLoading: false
        searching: false
