CREATE TABLE IF NOT EXISTS "Interactions" (
    "Id" bigint NOT NULL,
    "ChannelId" bigint NOT NULL,
    "ApplicationId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "GuildId" bigint NULL,
    "Username" text NOT NULL,
    "GlobalName" text NULL,
    "Nickname" text NULL,
    "Data" jsonb NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Interactions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Reminders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId" bigint NOT NULL,
    "ChannelId" bigint NOT NULL,
    "ReminderMessage" text NOT NULL,
    "DueAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "ClaimedAt" timestamp with time zone NULL,
    "SentAt" timestamp with time zone NULL,
    "AttemptCount" integer NOT NULL,
    "LastError" text NULL,
    CONSTRAINT "PK_Reminders" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_Reminders_Status_DueAt"
    ON "Reminders" ("Status", "DueAt");

CREATE INDEX IF NOT EXISTS "IX_Reminders_UserId_Status_DueAt"
    ON "Reminders" ("UserId", "Status", "DueAt");

CREATE TABLE IF NOT EXISTS "ApiCredentials" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OwnerDiscordUserId" bigint NOT NULL,
    "Name" text NOT NULL,
    "ClientId" text NOT NULL,
    "SecretHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastUsedAt" timestamp with time zone NULL,
    "RevokedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_ApiCredentials" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ApiCredentials_ClientId"
    ON "ApiCredentials" ("ClientId");

CREATE INDEX IF NOT EXISTS "IX_ApiCredentials_OwnerDiscordUserId"
    ON "ApiCredentials" ("OwnerDiscordUserId");

CREATE TABLE IF NOT EXISTS "MusicFavorites" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "DiscordUserId" bigint NOT NULL,
    "Kind" text NOT NULL,
    "ExternalId" text NOT NULL,
    "Title" text NOT NULL,
    "ArtistOrSubtitle" text NOT NULL,
    "SourceName" text NOT NULL,
    "SourceUrl" text NOT NULL,
    "ArtworkUrl" text NOT NULL,
    "MetadataJson" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MusicFavorites" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_MusicFavorites_DiscordUserId_Kind_CreatedAt"
    ON "MusicFavorites" ("DiscordUserId", "Kind", "CreatedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MusicFavorites_DiscordUserId_Kind_ExternalId"
    ON "MusicFavorites" ("DiscordUserId", "Kind", "ExternalId");

CREATE TABLE IF NOT EXISTS "GuildTrackPlays" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GuildId" bigint NOT NULL,
    "ExternalId" text NOT NULL,
    "Title" text NOT NULL,
    "Artist" text NOT NULL,
    "SourceName" text NOT NULL,
    "SourceUrl" text NOT NULL,
    "ArtworkUrl" text NOT NULL,
    "PlayCount" bigint NOT NULL,
    "FirstPlayedAt" timestamp with time zone NOT NULL,
    "LastPlayedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GuildTrackPlays" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GuildTrackPlays_GuildId_ExternalId"
    ON "GuildTrackPlays" ("GuildId", "ExternalId");

CREATE INDEX IF NOT EXISTS "IX_GuildTrackPlays_GuildId_PlayCount_LastPlayedAt"
    ON "GuildTrackPlays" ("GuildId", "PlayCount", "LastPlayedAt");
