name: Deploy Staging

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "infra/**"
      - ".github/workflows/**"
      - "Directory.Build.props"
      - "Directory.Packages.props"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    concurrency:
      group: deploy-staging
      cancel-in-progress: false
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit
