name: Deploy

on:
  # Trigger on merge to main
  workflow_run:
    workflows: [ "Build and Test" ]
    branches: [ main ]
    types:
      - completed
  # Manual trigger for prod deployments
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        required: true
        default: 'prd'
        type: choice
        options:
          - prd
          - stg

env:
  API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
  ARCHITECTURE: x86_64
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
  ENVIRONMENT: 'prd'
  NEON_CONNECTION_STRING: ${{ secrets.NEON_CONNECTION_STRING }}

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore the project
      - name: Restore project
        run: dotnet restore infra/WasabiBot.MigrationsRunner

      # Build the project
      - name: Build project
        run: dotnet build infra/WasabiBot.MigrationsRunner --no-restore --tl

      # Migrate the database
      - name: Migrate database
        run: dotnet run --project infra/WasabiBot.MigrationsRunner --no-build --tl

  deploy:
    runs-on: ubuntu-latest
    needs: migrate

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # run cdktf
      # tf init
      # apply terraform
      # Deploy to Fly.io
