name: Deploy Application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment to deploy to (staging/production)'
    secrets:
      PG_CONNECTION_STRING:
        required: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Restore the project
      - name: Restore project
        run: dotnet restore tools/WasabiBot.MigrationsRunner

      # Build the project
      - name: Build project
        run: dotnet build tools/WasabiBot.MigrationsRunner --no-restore --tl

      # Migrate the database
      - name: Migrate database
        env:
          ConnectionStrings__Postgres: ${{ secrets.PG_CONNECTION_STRING }}
        run: dotnet run --project tools/WasabiBot.MigrationsRunner --no-build --tl

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [migrate]
    concurrency:
      group: $ENVIRONMENT
      cancel-in-progress: false
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Flyctl
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy to Fly.io
      - name: Deploy to Fly.io
        run: flyctl deploy --config ./src/WasabiBot.Web/fly.$ENVIRONMENT.toml --dockerfile ./src/WasabiBot.Web/Dockerfile --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}