name: Deploy Production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  lavalink:
    needs: tests
    uses: ./.github/workflows/deploy-lavalink.yml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      LAVALINK_PASSWORD: ${{ secrets.LAVALINK_PASSWORD }}

  deploy:
    needs: tests
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      fly-app: wasabi-bot-prod
      fly-config: fly.prod.toml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
