name: Deploy to Staging

on:
  push:
    branches: [ main ]

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets:
      PG_CONNECTION_STRING: ${{ secrets.PG_CONNECTION_STRING }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
