name: Deploy Fly Staging

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "Directory.Build.props"
      - "Directory.Packages.props"
      - "src/WasabiBot.Api/fly.db.toml"
      - "src/WasabiBot.Api/fly.staging.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-fly.yml
    with:
      environment: staging
      fly-config: src/WasabiBot.Api/fly.staging.toml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
