name: Run Database Migrations

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g. production, staging)'
        required: true
        default: 'staging'
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'src/WasabiBot.DataAccess/**'
  #     - 'src/WasabiBot.Migrations/**'
  #     - '.github/workflows/run-migrations.yml'

permissions:
  contents: read
  id-token: write

jobs:
  migrate:
    name: Apply EF Core migrations
    runs-on: ubuntu-latest

    # Allow selecting an environment for secret scoping
    environment: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/*.props

      - name: Restore
        run: dotnet restore

      - name: Build migrations project
        run: dotnet build src/WasabiBot.Migrations/WasabiBot.Migrations.csproj --configuration Release --no-restore

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_AWS_ROLE }}
          aws-region: us-east-1

      - name: Run migrations
        env:
          ConnectionStrings__wasabi-db: ${{ secrets.PG_CONNECTION_STRING }}
        run: dotnet run --project src/WasabiBot.Migrations/WasabiBot.Migrations.csproj --configuration Release --no-build
